version: '3.1'

services:
  rdb:
    image: redis:7-alpine
    restart: always
    env_file:
      - '.env'
    command: 'redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}'
    volumes:
      - db-data:/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - 'linux/amd64'
    restart: on-failure
    env_file:
      - '.env'
    depends_on:
      rdb:
        condition: service_started
    ports:
      - '8080:8080'
    environment:
      PORT: 8080
      REDIS_URL: 'redis://default:${REDIS_PASSWORD}@rdb:6379'
      DOMAIN_NAME: ${DOMAIN_NAME}

volumes:
  db-data:

